services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - '63122:6379'

  postgres:
    container_name: postgres
    image: "postgres:15.6-alpine3.19"
    restart: unless-stopped
    ports:
      - '54522:5432'
    networks:
      - interconnect
      - postgres.network
    env_file:
      - "./.env"
    environment:
      POSTGRES_USER: ${DB_USER:-$USER}
      POSTGRES_DB: ${DB_NAME:-$USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  nats:
    container_name: 'nats'
    image: 'nats:latest'
    restart: 'unless-stopped'
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    command: 
      - "--config"
      - "/etc/nats/nats.conf"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
      - nats_data:/nats-assets/assets
    networks:
      - interconnect


volumes:
  postgres.data: {}
  nats_data: {}
networks:
  interconnect:
    driver: bridge
  postgres.network: {}
