"""unique

Revision ID: 02_82e484eb7a8e
Revises: 01_3d1a9bc30546
Create Date: 2025-04-12 01:53:21.346825

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02_82e484eb7a8e"
down_revision: Union[str, None] = "01_3d1a9bc30546"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_login", table_name="user")
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.create_index("ix_user_login", "user", ["login"], unique=False)
    # ### end Alembic commands ###
